version: "3"

services:
  web: &web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/ruby-hl7/
    command: >
      bash -c "echo \"'docker-compose exec web bin/console' to run irb\"
      && (tail -f /dev/null)"
